-module(generated_test).
-export([main/0]).

% Erlang Test Script.

% Generated by the python script "generate_random events.py"
% This file executes N processes with M random communications
% between them (N and M are chosen via the python script)

% Nb of processes: 10
% Nb of communications: 10

main() ->
		GLOBAL = messenger:start_N_processes(10),
		messenger:send(6, 3, GLOBAL),
		messenger:send(0, 6, GLOBAL),
		messenger:send(0, 3, GLOBAL),
		messenger:send(1, 1, GLOBAL),
		messenger:send(7, 6, GLOBAL),
		messenger:send(4, 9, GLOBAL),
		messenger:send(4, 6, GLOBAL),
		messenger:send(7, 9, GLOBAL),
		messenger:send(7, 1, GLOBAL),
		messenger:send(8, 0, GLOBAL).
